frontend:
  enabled: false

backend:
  env:
    ALLOWED_HOSTS: "localhost,127.0.0.1,10.0.0.140,backend,*"
    CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://10.0.0.145:3000"
    CSRF_TRUSTED_ORIGINS: "http://localhost:3000,http://10.0.0.145:3000"

service:
  backend:
    type: NodePort
    port: 8000
    nodePort: 30080
