apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "maple-syrup-store.fullname" . }}-backend
  labels:
    {{- include "maple-syrup-store.labels" . | nindent 4 }}
    app: backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "maple-syrup-store.selectorLabels" . | nindent 6 }}
      app: backend
  template:
    metadata:
      labels:
        {{- include "maple-syrup-store.selectorLabels" . | nindent 8 }}
        app: backend
    spec:
      containers:
      - name: backend
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        ports:
        - containerPort: 8000
        env:
        {{- range $key, $value := .Values.backend.env }}
        - name: {{ $key }}
          value: "{{ $value }}"
        {{- end }}
        {{- range $key, $value := .Values.backend.secrets }}
        - name: {{ $key }}
          value: "{{ $value }}"
        {{- end }}
        {{- if .Values.django.superuser }}
        {{- if .Values.django.superuser.username }}
        - name: DJANGO_SUPERUSER_USERNAME
          value: "{{ .Values.django.superuser.username }}"
        {{- end }}
        {{- if .Values.django.superuser.email }}
        - name: DJANGO_SUPERUSER_EMAIL
          value: "{{ .Values.django.superuser.email }}"
        {{- end }}
        {{- if .Values.django.superuser.password }}
        - name: DJANGO_SUPERUSER_PASSWORD
          value: "{{ .Values.django.superuser.password }}"
        {{- end }}
        {{- end }}
        resources:
          {{- toYaml .Values.backend.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    {{- include "maple-syrup-store.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    {{- include "maple-syrup-store.selectorLabels" . | nindent 4 }}
    app: backend
