apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "maple-syrup-store.fullname" . }}-frontend
  labels:
    {{- include "maple-syrup-store.labels" . | nindent 4 }}
    app: frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "maple-syrup-store.selectorLabels" . | nindent 6 }}
      app: frontend
  template:
    metadata:
      labels:
        {{- include "maple-syrup-store.selectorLabels" . | nindent 8 }}
        app: frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
        - containerPort: 80
        resources:
          {{- toYaml .Values.frontend.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    {{- include "maple-syrup-store.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    {{- include "maple-syrup-store.selectorLabels" . | nindent 4 }}
    app: frontend
