apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "maple-syrup-store.fullname" . }}-pdf-service
  labels:
    {{- include "maple-syrup-store.labels" . | nindent 4 }}
    app: pdf-service
spec:
  replicas: {{ .Values.pdfService.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "maple-syrup-store.selectorLabels" . | nindent 6 }}
      app: pdf-service
  template:
    metadata:
      labels:
        {{- include "maple-syrup-store.selectorLabels" . | nindent 8 }}
        app: pdf-service
    spec:
      containers:
      - name: pdf-service
        image: "{{ .Values.pdfService.image.repository }}:{{ .Values.pdfService.image.tag }}"
        imagePullPolicy: {{ .Values.pdfService.image.pullPolicy }}
        ports:
        - containerPort: 8000
        env:
        - name: PDF_STORAGE_DIR
          value: "/tmp/receipts"
        resources:
          {{- toYaml .Values.pdfService.resources | nindent 12 }}
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: pdf-service
  labels:
    {{- include "maple-syrup-store.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    {{- include "maple-syrup-store.selectorLabels" . | nindent 4 }}
    app: pdf-service
