apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "maple-syrup-store.fullname" . }}-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage.size }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "maple-syrup-store.fullname" . }}-postgres
  labels:
    {{- include "maple-syrup-store.labels" . | nindent 4 }}
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "maple-syrup-store.selectorLabels" . | nindent 6 }}
      app: postgres
  template:
    metadata:
      labels:
        {{- include "maple-syrup-store.selectorLabels" . | nindent 8 }}
        app: postgres
    spec:
      containers:
      - name: postgres
        image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
        ports:
        - containerPort: 5432
        env:
        {{- range $key, $value := .Values.postgres.env }}
        - name: {{ $key }}
          value: "{{ $value }}"
        {{- end }}
        {{- range $key, $value := .Values.postgres.secrets }}
        - name: {{ $key }}
          value: "{{ $value }}"
        {{- end }}
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: {{ include "maple-syrup-store.fullname" . }}-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    {{- include "maple-syrup-store.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    {{- include "maple-syrup-store.selectorLabels" . | nindent 4 }}
    app: postgres
